# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 14:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bomb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('duration_starting', models.DateTimeField()),
                ('duration_ending', models.DateTimeField()),
                ('brange', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='bombs/')),
                ('user_change_location', models.BooleanField(default=False)),
                ('change_location', models.BooleanField(default=False)),
                ('stealth', models.BooleanField(default=False)),
                ('simultaneous', models.BooleanField(default=False)),
            ],
        ),
    ]
