# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bombs', '0002_auto_20170111_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bomb',
            new_name='BombType',
        ),
    ]
